apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-snapshot-binding
  namespace: kube-system
subjects:
- kind: User
  name: "naufal"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: etcd-snapshot-role
  apiGroup: rbac.authorization.k8s.io
