apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: etcd-snapshot-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "etcd-snapshots"]
  verbs: ["get", "list", "create", "delete"]
